version: 1.0.0.{build}

image: Visual Studio 2019

platform: Any CPU
configuration: Release

before_build:
  ps: (Get-Content SetScrTimeout\Properties\AssemblyInfo.cs) -replace '(AssemblyFileVersion\("\d+\.\d+\.\d+)(\.0)("\))', ('$1.'+$Env:APPVEYOR_BUILD_NUMBER+'$3') | Out-File -Encoding UTF8 SetScrTimeout\Properties\AssemblyInfo.cs

build:
  project: SetScrTimeout.sln

after_build:
  ps: Get-FileHash -Algorithm SHA256 SetScrTimeout\bin\$Env:CONFIGURATION\*.* | Format-List

artifacts:
  - path: SetScrTimeout\bin\$(configuration)\*.*
